### ISSUE TITLE
[Feature/Bug] holding item rolls crazy fast if turns fullscreen on and off a lot

### ISSUE THREAD

**Issue by x-yingcan-x** [Octo-Studios/immersive-ui#4]
i know mod works as intended, but pretty fun, i hope for a feature like when u moving ur mouse very fast, the item will do a roll, not just swing

**Comment by slushieuwu** [comment]
Honestly, full physics would be really fun to have :p

**Comment by catboybinary** [comment]
Fixed in the latest update (hopefully), also, you can now configure the swinging strength in the config file.
