### ISSUE TITLE
[Suggestion] Could you allow the slot highlight indicator to still be present?

### ISSUE THREAD

**Issue by slushieuwu** [Octo-Studios/immersive-ui#5]
A small nitpick, i just like having the visual feedback of which slot im hovering over :p

The indicator in question:

https://github.com/Octo-Studios/immersive-ui/assets/86991346/91570a9a-2df5-43ef-965b-e59141fda3ad

Currently with the mod:

https://github.com/Octo-Studios/immersive-ui/assets/86991346/08b0e2c7-ffac-4464-b456-a247e0926a4e

**Comment by slushieuwu** [comment]
Preferrably under items as well, just all slots as it is in vanilla

**Comment by memphismc** [comment]
i second this

**Comment by catboybinary** [comment]
Present as default option in the mod right now. Can be disabled via config file.
